### ISSUE TITLE
libpng error: Too many IDATs found!

### ISSUE THREAD

**Issue by Adesun** [dmlc/cxxnet#125]
it displayed error as follows  when training cifar images.

initializing end, start working
round        0:[     100] 56 sec elapsedlibpng error: Too many IDATs found
OpenCV Error: Assertion failed (src.cols > 0 && src.rows > 0) in cv::warpAffine,
 file C:\builds\2_4_PackSlave-win64-vc12-shared\opencv\modules\imgproc\src\imgwa
rp.cpp, line 3591

it's werid that the format of cifar image is jpg ! 
what should I do next?
thanks!

**Comment by antinucleon** [comment]
I am not sure how you deal with cifar. I have script to convert cifar python format to jpeg then pack it into binary file, then use imgbinx to do iteration. It works fine. How did you run it?

**Comment by Adesun** [comment]
actually I  did pack cifar images to binary file using im2bin.exe successfully.
there's the similar error when training with binary file. >_<

initializing end, start working
round        0:[     300] 156 sec elapsedlibpng error: Too many IDATs found
AssertError:decoding fail

**Comment by antinucleon** [comment]
This is my script to covert official cifar python pkl file to images, then I pack it into bin. 
```python
import os
import sys
import pickle
import csv
import numpy as np
from PIL import Image

if len(sys.argv) < 3:
    print "usage: convert cifar.pkl output_root_folder_path output_list_path"
    exit(-1)

cifar = pickle.load(file(sys.argv[1]))
root = sys.argv[2]
try:
    os.mkdir(root)
except:
    print "%s exists, ignore"

fo = csv.writer(open(sys.argv[3], "w"), lineterminator='\n', delimiter='\t')

data = cifar['data']
label = cifar['fine_labels']
path = cifar['filenames']

sz = data.shape[0]

for i in xrange(sz):
    if i % 1000 == 0:
        print i
    img = data[i]
    p = path[i]
    img = img.reshape((3, 32, 32))
    img = np.swapaxes(img, 0, 2)
    img = np.swapaxes(img, 0, 1)
    im = Image.fromarray(img)
    im.save(root + p)
    row = [i, label[i], p]
    fo.writerow(row)

```

**Comment by Adesun** [comment]
I used the python scripts from project DIGITS of NVIDIA to extract images from cifar binary file.
https://github.com/NVIDIA/DIGITS/tree/master/tools/download_data
then pack images extracted into binary file by im2bin.exe.

the config modified as follows:
```
data = train
iter = imgbin
  image_list = "./cifar/train.txt"
  image_bin  = "./cifar/TRAIN.BIN"
  rand_crop=1
  rand_mirror=1
iter = threadbuffer
iter = end

eval = test
iter = imgbin
  image_list = "./cifar/test.txt"
  image_bin = "./cifar/TEST.BIN"
# no random crop and mirror in test
iter = end

netconfig=start
layer[0->1] = conv
  kernel_size = 11
  stride = 4
  nchannel = 96
layer[1->2] = relu
layer[2->3] = max_pooling
  kernel_size = 3
  stride = 2
layer[3->4] = lrn
  local_size = 5
  alpha = 0.001
  beta = 0.75
  knorm = 1
###############
layer[4->5] = conv
  ngroup = 2
  nchannel = 256
  kernel_size = 5
  pad = 2
layer[5->6] = relu
layer[6->7] = max_pooling
  kernel_size = 3
  stride = 2
layer[7->8] = lrn
  local_size = 5
  alpha = 0.001
  beta = 0.75
  knorm = 1
#############
layer[8->9] = conv
  nchannel = 384
  kernel_size = 3
  pad = 1
layer[9->10]= relu
layer[10->11] = conv
  nchannel = 384
  ngroup = 2
  kernel_size = 3
  pad = 1
layer[11->12] = relu
layer[12->13] = conv
  nchannel = 256
  ngroup = 2
  kernel_size = 3
  pad = 1
  init_bias = 1.0
layer[13->14] = relu
layer[14->15] = max_pooling
  kernel_size = 3
  stride = 2
layer[15->16] = flatten
layer[16->17] = fullc
  nhidden = 4096
  init_sigma = 0.005
  init_bias = 1.0
layer[17->18] = relu
layer[18->18] = dropout
  threshold = 0.5
layer[18->19] = fullc
  nhidden = 4096
  init_sigma = 0.005
  init_bias = 1.0
layer[19->20] = relu
layer[20->20] = dropout
  threshold = 0.5
layer[20->21] = fullc
  nhidden = 1000
layer[21->21] = softmax
netconfig=end

# evaluation metric
metric = error
metric = rec@1
metric = rec@5

max_round = 45
num_round = 45

# input shape not including batch
input_shape = 3,227,227

#update_period=2
batch_size = 64

# global parameters in any sectiion outside netconfig, and iter
momentum = 0.9
wmat:lr  = 0.01
wmat:wd  = 0.0005

bias:wd  = 0.000
bias:lr  = 0.02

# all the learning rate schedule starts with lr
lr:schedule = expdecay
lr:gamma = 0.1
lr:step = 100000

save_model=1
model_dir=models

# random config
random_type = xavier


# new line
```

**Comment by antinucleon** [comment]
I am not sure about DIGIT's script, but I am sure my script works.

**Comment by Adesun** [comment]
Hi,
Thank you very much for you reply! 
I tried the code you posted,
but some error occurred when unpacking cifar-100 binary file using ths script.
```
python un.py test.bin ./out/ ./out/test.txt

Traceback (most recent call last):
  File "un.py", line 12, in <module>
    cifar = pickle.load(file(sys.argv[1]))
  File "...\lib\pickle.py", line 1378, in load
    return Unpickler(file).load()
  File "....\lib\pickle.py", line 858, in load
    dispatch[key](self)
KeyError: '\n'

```

**Comment by antinucleon** [comment]
You use wrong file for parameter 1. This is CIFAR-10 data:http://www.cs.toronto.edu/~kriz/cifar.html

**Comment by antinucleon** [comment]
Download the Python version data, then use the script like python convert.py train train/ train.lst

**Comment by Adesun** [comment]
I got it. I thought it would work with cifar-100.
actually I was totally wrong.
thanks!
